### ISSUE TITLE
- /usr/local/lib/python3.6/asyncio/events.py[line:145] - INFO: 青龙-1 登录失败 'data' 不支持python3.6？

### ISSUE THREAD

**Issue by fetisherst** [xieshang/AutoSpy#14]
2022-11-04 21:46:09,868 - /usr/local/lib/python3.6/asyncio/events.py[line:145] - INFO: 青龙-1 登录失败
'data'
^CException ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x7faa5aebf5c0>>
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/aiohttp/client.py", line 343, in __del__
TypeError: 'NoneType' object is not callable

**Comment by yanghonghao6789** [comment]
你装大赢家了吧  这个插件在我这报错

**Comment by cyz0105** [comment]
> 2022-11-04 21:46:09,868 - /usr/local/lib/python3.6/asyncio/events.py[line:145] - INFO: 青龙-1 登录失败 'data' ^CException ignored in: <bound method ClientSession.**del** of <aiohttp.client.ClientSession object at 0x7faa5aebf5c0>> Traceback (most recent call last): File "/root/.local/lib/python3.6/site-packages/aiohttp/client.py", line 343, in **del** TypeError: 'NoneType' object is not callable

这种情况只能等作者更新了,青龙新版本api返回值改变了,原来用'data'键可以获取到的值,现在必须在'data'下的'data'才可以. 要修复,请考虑使用2.11.3版本的青龙.
