### ISSUE TITLE
不论是在Docker还是在本地环境下均会出现错误

### ISSUE THREAD

**Issue by Tinyu-Zhao** [xieshang/AutoSpy#16]
执行命令python3 auto_spy_bot.py后会出现

`[root@VM-20-14-centos autospy]# pip3 install --user -U asyncio  pyyaml telethon snowland-smx httpx pysocks requests
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already up-to-date: asyncio in /root/.local/lib/python3.6/site-packages
Requirement already up-to-date: pyyaml in /root/.local/lib/python3.6/site-packages
Requirement already up-to-date: telethon in /root/.local/lib/python3.6/site-packages
Requirement already up-to-date: snowland-smx in /root/.local/lib/python3.6/site-packages
Requirement already up-to-date: httpx in /root/.local/lib/python3.6/site-packages
Requirement already up-to-date: pysocks in /root/.local/lib/python3.6/site-packages
Requirement already up-to-date: requests in /root/.local/lib/python3.6/site-packages
Requirement already up-to-date: pyaes in /root/.local/lib/python3.6/site-packages (from telethon)
Requirement already up-to-date: rsa in /root/.local/lib/python3.6/site-packages (from telethon)
Requirement already up-to-date: sniffio in /root/.local/lib/python3.6/site-packages (from httpx)
Requirement already up-to-date: httpcore<0.15.0,>=0.14.5 in /root/.local/lib/python3.6/site-packages (from httpx)
Requirement already up-to-date: certifi in /root/.local/lib/python3.6/site-packages (from httpx)
Requirement already up-to-date: rfc3986[idna2008]<2,>=1.3 in /root/.local/lib/python3.6/site-packages (from httpx)
Requirement already up-to-date: charset-normalizer in /root/.local/lib/python3.6/site-packages (from httpx)
Requirement already up-to-date: async-generator; python_version < "3.7" in /root/.local/lib/python3.6/site-packages (from httpx)
Requirement already up-to-date: idna<4,>=2.5; python_version >= "3" in /root/.local/lib/python3.6/site-packages (from requests)
Requirement already up-to-date: urllib3<1.27,>=1.21.1 in /root/.local/lib/python3.6/site-packages (from requests)
Requirement already up-to-date: pyasn1>=0.1.3 in /root/.local/lib/python3.6/site-packages (from rsa->telethon)
Requirement already up-to-date: contextvars>=2.1; python_version < "3.7" in /root/.local/lib/python3.6/site-packages (from sniffio->httpx)
Requirement already up-to-date: h11<0.13,>=0.11 in /root/.local/lib/python3.6/site-packages (from httpcore<0.15.0,>=0.14.5->httpx)
Requirement already up-to-date: anyio==3.* in /root/.local/lib/python3.6/site-packages (from httpcore<0.15.0,>=0.14.5->httpx)
Requirement already up-to-date: immutables>=0.9 in /root/.local/lib/python3.6/site-packages (from contextvars>=2.1; python_version < "3.7"->sniffio->httpx)
Requirement already up-to-date: typing-extensions; python_version < "3.8" in /root/.local/lib/python3.6/site-packages (from anyio==3.*->httpcore<0.15.0,>=0.14.5->httpx)
Requirement already up-to-date: dataclasses; python_version < "3.7" in /root/.local/lib/python3.6/site-packages (from anyio==3.*->httpcore<0.15.0,>=0.14.5->httpx)
[root@VM-20-14-centos autospy]# python3 auto_spy_bot.py
sys info:uname_result(system='Linux', node='VM-20-14-centos', release='3.10.0-1160.76.1.el7.x86_64', version='#1 SMP Wed Aug 10 16:21:17 UTC 2022', machine='x86_64', processor='x86_64')
系统为 x86_tx
/root/.local/lib/python3.6/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (None)/charset_normalizer (3.0.0) doesn't match a supported version!
  RequestsDependencyWarning)
No module named 'aiohttp'
缺依赖，尝试进行修复，也可手动修复： pip3 install --user python-socks[asyncio] python-socks requests[socks] pysocks requests asyncio telethon==1.24.0 pyyaml httpx anyio snowland-smx
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: snowland-smx in /root/.local/lib/python3.6/site-packages
Requirement already satisfied: python-socks[asyncio] in /root/.local/lib/python3.6/site-packages
Requirement already satisfied: requests[socks] in /root/.local/lib/python3.6/site-packages
Requirement already satisfied: pysocks in /root/.local/lib/python3.6/site-packages
Requirement already satisfied: asyncio in /root/.local/lib/python3.6/site-packages
Collecting telethon==1.24.0
  Downloading http://mirrors.tencentyun.com/pypi/packages/f5/2a/238c14ad6032d91ff134723d48470f8c5fe521522af323fde10c34e23047/Telethon-1.24.0-py3-none-any.whl (528kB)
    100% |████████████████████████████████| 532kB 14.2MB/s 
Requirement already satisfied: pyyaml in /root/.local/lib/python3.6/site-packages
Requirement already satisfied: httpx in /root/.local/lib/python3.6/site-packages
Requirement already satisfied: anyio in /root/.local/lib/python3.6/site-packages
Collecting aiohttp
  Downloading http://mirrors.tencentyun.com/pypi/packages/ff/4f/62d9859b7d4e6dc32feda67815c5f5ab4421e6909e48cbc970b6a40d60b7/aiohttp-3.8.3.tar.gz (7.3MB)
    100% |████████████████████████████████| 7.3MB 31.5MB/s 
    Complete output from command python setup.py egg_info:
    *********************
    * Accelerated build *
    *********************
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ct6vlgtr/aiohttp/setup.py", line 54, in <module>
        setup(**setup_kwargs)
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 121, in setup
        dist.parse_config_files()
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 495, in parse_config_files
        ignore_option_errors=ignore_option_errors)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 111, in parse_configuration
        meta.parse()
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 397, in parse
        section_parser_method(section_options)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 370, in parse_section
        self[name] = value
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 174, in __setitem__
        value = parser(value)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 463, in _parse_version
        version = self._parse_attr(value, self.package_dir)
      File "/usr/lib/python3.6/site-packages/setuptools/config.py", line 320, in _parse_attr
        module = import_module(module_name)
      File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/tmp/pip-build-ct6vlgtr/aiohttp/aiohttp/__init__.py", line 5, in <module>
        from . import hdrs as hdrs
      File "/tmp/pip-build-ct6vlgtr/aiohttp/aiohttp/hdrs.py", line 8, in <module>
        from multidict import istr
    ModuleNotFoundError: No module named 'multidict'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ct6vlgtr/aiohttp/
Traceback (most recent call last):
  File "auto_spy.py", line 50, in auto_spy
ModuleNotFoundError: No module named 'aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "auto_spy_bot.py", line 28, in <module>
    from auto_spy import main
  File "auto_spy.py", line 70, in init auto_spy
ModuleNotFoundError: No module named 'numpy'
[root@VM-20-14-centos autospy]# python auto_spy_bot.py
  File "auto_spy_bot.py", line 14
SyntaxError: Non-ASCII character '\xe7' in file auto_spy_bot.py on line 14, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[root@VM-20-14-centos autospy]# `

**Comment by Richar-Song** [comment]
应该是缺"numpy" 依赖，用pip install numpy可以装上，刚搞成功
