### ISSUE TITLE
The authorization key (session file) was used under two different IP addresses simultaneously, and can no longer be used

### ISSUE THREAD

**Issue by sailcom** [xieshang/AutoSpy#17]
请问这个提示就是黑号了吗？
如何解决呢？
我在v2ray机场同时选择了好几个节点，是因为这个原因引起的吗？
感谢解答！

![未命名 2](https://user-images.githubusercontent.com/42264621/202461978-6c8e2514-12fe-42d3-8301-5d3edb2dc842.png)

**Comment by xieshang** [comment]
tg判定同一个授权在不同ip中同时登录了，停止容器，删除目录下autospy.session文件，然后启动容器，按照安装教程里的登录开始操作一遍就可以了。
