### ISSUE TITLE
想知道spy容器有没有端口号 

### ISSUE THREAD

**Issue by yanghonghao6789** [xieshang/AutoSpy#18]
大佬你好，spy容器的默认端口号是多少？还是就没有端口号，我这边的环境是openwrt的docker里跑spy，如果有端口，我openwrt的adguardhome就可以看到spy 的访问情况，就像我的青龙 可以看到青龙都访问哪些  
容器默认桥接，创建容器时比如青龙的 5200:5700   这样adg就会显示   没有端口的 访问数据应该都归到local里面了  所以想知道spy的默认端口  可以不改变  哪怕是默认5700:5700都管用  
![image](https://user-images.githubusercontent.com/73630536/203350876-8af5752d-cec0-45f1-b968-0490ff0fdc4f.png)

**Comment by yanghonghao6789** [comment]
![image](https://user-images.githubusercontent.com/73630536/203355645-133c9940-2423-45aa-94e5-05cd4bf0e21f.png)
刚看了一下 spy没有默认端口号   这样还真不好办  希望以后版本能够增加一个默认端口 tglog关闭了 自己可以看adg里面的访问情况判断是否断联

**Comment by xieshang** [comment]
没有端口号，因为并没有提供http接口
