### ISSUE TITLE
请问这种报错改怎么解决

### ISSUE THREAD

**Issue by 1312007470** [xieshang/AutoSpy#19]
![photo_2022-11-23_03-05-04](https://user-images.githubusercontent.com/35362226/203401293-c7d10c12-bfcc-442f-84a2-816606875fdc.jpg)
大佬，请问这种报错改怎么解决

**Comment by 1312007470** [comment]
本地青龙

**Comment by cyz0105** [comment]
> 本地青龙

仔细检查格式,yaml文件:的后面要有一个空格

**Comment by xieshang** [comment]
配置文件错误，推荐排查问题的时候，把错误信息复制下来去百度翻译看下，基本可以看懂的。
spy出错除了程序问题，就是配置文件问题

配置文件24,25行应该有问题，具体的要自己看下，记得英文冒号后面要留空格
