### ISSUE TITLE
能否增加环境变量“追加”功能？

### ISSUE THREAD

**Issue by 592732377** [xieshang/AutoSpy#20]
现状：目前环境变量都是以“改写”模式，将原有变量全部换新。
问题：部分环境变量不适合一次性全部替换，如“店铺签到”中的"DPQDTK"，这类变量只适合在原变量上继续追加新变量。
解决方法：建议在监控对象里增加一个配置选型

**Comment by xieshang** [comment]
如果只是签到，用签到插件即可；
