### ISSUE TITLE
不支持青龙新版本2.15

### ISSUE THREAD

**Issue by OwnerCM** [xieshang/AutoSpy#34]
AutoSpy目前不支持青龙新版本，请问大佬是否会进行适配？
如无适配计划，请问支持的青龙最新版本是哪个？
感谢大佬提供这么方便的工具，谢谢！

**Comment by insoxin** [comment]
同问,支持到最新哪个版本了?

**Comment by xieshang** [comment]
不好意思，平时不怎么看库，应该已经支持了吧？
