### ISSUE TITLE
青龙登录失败

### ISSUE THREAD

**Issue by Aexus** [xieshang/AutoSpy#35]
<img width="984" alt="image" src="https://user-images.githubusercontent.com/3403478/211289317-f6d03c5c-3e83-49a5-8b85-1927d9ec106e.png">
有显示登录成功,下一行显示失败.请问哪里配置有问题吗?
青龙版本: 2.11.3 AutoSpy V2023-01-06

**Comment by Joyrocky** [comment]
> <img alt="image" width="984" src="https://user-images.githubusercontent.com/3403478/211289317-f6d03c5c-3e83-49a5-8b85-1927d9ec106e.png">
> 
> 有显示登录成功,下一行显示失败.请问哪里配置有问题吗? 青龙版本: 2.11.3 AutoSpy V2023-01-06

我也是这样，青龙版本2.13.9  autospy 版本为V2023-01-06，不过我是`青龙-1 登录失败 code`，你的青龙配置是什么，内网IP嘛？

**Comment by Aexus** [comment]
> > <img alt="image" width="984" src="https://user-images.githubusercontent.com/3403478/211289317-f6d03c5c-3e83-49a5-8b85-1927d9ec106e.png">
> > 有显示登录成功,下一行显示失败.请问哪里配置有问题吗? 青龙版本: 2.11.3 AutoSpy V2023-01-06
> 
> 我也是这样，青龙版本2.13.9 autospy 版本为V2023-01-06，不过我是`青龙-1 登录失败 code`，你的青龙配置是什么，内网IP嘛？ ![image](https://user-images.githubusercontent.com/23481533/212339156-8a4a2541-bc66-4cc7-b79f-73578d09b60a.png)

删除镜像并清空所有配置目录.再重新部署就没问题了.你试试
