### ISSUE TITLE
string indices must be integers 字符串错误

### ISSUE THREAD

**Issue by 841194253** [xieshang/AutoSpy#6]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/48153306/194461518-c9cf8e7b-2fea-4c0c-ad45-972adfa043b8.png">

如果开发者有时间的话，请看看小弟的错误吧

**Comment by 592732377** [comment]
版本问题，参考关闭的issues

**Comment by 592732377** [comment]
最高到2.13.8

**Comment by 841194253** [comment]
> 最高到2.13.8

谢谢大佬，知道了
